jenkinsdata:
 build: jenkins-data
 
jenkinsmaster:
  build: jenkins-master
  volumes_from:
    - jenkinsdata
  ports:
    - "50000:50000"

jenkinsnginx:
  build: jenkins-nginx
  ports:
     - "6080:80" # Need to make this configurable, as we'll want 80:80 in 'prod' environments
  links:
     - jenkinsmaster:jenkinsmaster
